POST http://localhost:5000/api/users/signup
content-type: application/json

{
    "name": "Randak",
    "username": "@randak",
    "password": "1234"
}

###
POST http://localhost:5000/api/users/login
Content-Type: application/json

{
    "username": "@desy",
    "password": "1234"
}

###
GET http://localhost:5000/api/users/